# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pymysql


class Ui_MainWindow(object):

    # database connection
    def dbcon(self):
        con = pymysql.connect(host="localhost", user="root",
                              password="", db="votingdb")
        return con

    def showTotalvotes(self):
        con = self.dbcon()
        
        selectQ1 = "select * from votes where vote_party = 'party1'"
        cursor = con.cursor()
        cursor.execute(selectQ1)
        party1TotalVotes = cursor.rowcount
        self.label_4.setNum(party1TotalVotes)

        selectQ2 = "select * from votes where vote_party = 'party2'"
        cursor = con.cursor()
        cursor.execute(selectQ2)
        party2TotalVotes = cursor.rowcount
        self.label_6.setNum(party2TotalVotes)

        selectQ3 = "select * from votes where vote_party = 'party3'"
        cursor = con.cursor()
        cursor.execute(selectQ3)
        party3TotalVotes = cursor.rowcount
        self.label_5.setNum(party3TotalVotes)
        con.commit()
        con.close()

    def message(self, title, msg):
        window = QtWidgets.QMessageBox()
        window.setWindowTitle(title)
        window.setText(msg)
        window.setStandardButtons(QtWidgets.QMessageBox.Ok)
        window.exec_()

    def registerVoter(self):
        con = self.dbcon()
        voterName = self.lineEdit.text()
        voterId = self.lineEdit_2.text()
        query = "Insert into voter(voter_name,voter_card) values(%s,%s)"
        cursor = con.cursor()
        run = cursor.execute(query, (voterName, voterId))

        if run:
            self.message("Success", "Voter Registered Successfully")
        con.commit()
        con.close()

    def registerParty(self):
        con = self.dbcon()
        partyName = self.lineEdit_4.text()
        partychar = self.lineEdit_3.text()
        query = "Insert into partydb(party_name,party_char) values(%s,%s)"
        cursor = con.cursor()
        run = cursor.execute(query, (partyName, partychar))

        if run:
            self.message("Success", "Party Registered Successfully")
        con.commit()
        con.close()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Arial")
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color:rgb(155, 182, 210)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(72, 44, 141, 61))
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("color:rgb(255, 255, 255);\n"
                                 "font-size:20px;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(320, 45, 141, 61))
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("color:rgb(255, 255, 255);\n"
                                   "font-size:20px;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(580, 44, 141, 61))
        self.label_3.setAutoFillBackground(False)
        self.label_3.setStyleSheet("color:rgb(255, 255, 255);\n"
                                   "font-size:20px;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(180, 50, 21, 51))
        self.label_4.setAutoFillBackground(False)
        self.label_4.setStyleSheet("color:rgb(255, 255, 255);\n"
                                   "font-size:20px;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(62, 93, 681, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(690, 50, 21, 51))
        self.label_5.setAutoFillBackground(False)
        self.label_5.setStyleSheet("color:rgb(255, 255, 255);\n"
                                   "font-size:20px;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(430, 50, 21, 51))
        self.label_6.setAutoFillBackground(False)
        self.label_6.setStyleSheet("color:rgb(255, 255, 255);\n"
                                   "font-size:20px;")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(40, 140, 141, 61))
        self.label_7.setAutoFillBackground(False)
        self.label_7.setStyleSheet("color:rgb(255, 255, 255);\n"
                                   "font-size:20px;\n"
                                   "background-color: rgb(106, 186, 255);\n"
                                   "border:2px solid white;")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 210, 141, 61))
        self.label_8.setAutoFillBackground(False)
        self.label_8.setStyleSheet("color:rgb(255, 255, 255);\n"
                                   "font-size:20px;")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(40, 320, 141, 61))
        self.label_9.setAutoFillBackground(False)
        self.label_9.setStyleSheet("color:rgb(255, 255, 255);\n"
                                   "font-size:20px;")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(50, 270, 281, 41))
        self.lineEdit.setAutoFillBackground(False)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                    "color: rgb(46, 54, 63);")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(50, 390, 281, 41))
        self.lineEdit_2.setAutoFillBackground(False)
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                      "color: rgb(46, 54, 63);")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(90, 510, 171, 31))
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("color: rgb(255, 255, 255);\n"
                                      "background-color: rgb(0, 0, 255);\n"
                                      "font-size:20px;\n"
                                      "border:2px solid white;")
        self.pushButton.setObjectName("pushButton")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(390, 120, 20, 451))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(440, 140, 141, 61))
        self.label_10.setAutoFillBackground(False)
        self.label_10.setStyleSheet("color:rgb(255, 255, 255);\n"
                                    "font-size:20px;\n"
                                    "background-color: rgb(106, 186, 255);\n"
                                    "border:2px solid white;")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(450, 390, 281, 41))
        self.lineEdit_3.setAutoFillBackground(False)
        self.lineEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                      "color: rgb(46, 54, 63);")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(440, 210, 141, 61))
        self.label_11.setAutoFillBackground(False)
        self.label_11.setStyleSheet("color:rgb(255, 255, 255);\n"
                                    "font-size:20px;")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(450, 270, 281, 41))
        self.lineEdit_4.setAutoFillBackground(False)
        self.lineEdit_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                      "color: rgb(46, 54, 63);")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(440, 320, 141, 61))
        self.label_12.setAutoFillBackground(False)
        self.label_12.setStyleSheet("color:rgb(255, 255, 255);\n"
                                    "font-size:20px;")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(500, 510, 171, 31))
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setStyleSheet("color: rgb(255, 255, 255);\n"
                                        "background-color: rgb(6, 152, 43);\n"
                                        "font-size:20px;\n"
                                        "border:2px solid white;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 10, 171, 31))
        self.pushButton_3.setAutoFillBackground(False)
        self.pushButton_3.setStyleSheet("\n"
                                        "background-color: rgb(255, 255, 0);\n"
                                        "font-size:20px;\n"
                                        "border:2px solid;")
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Admin Section"))
        self.label.setText(_translate("MainWindow", "Party 1 :"))
        self.label_2.setText(_translate("MainWindow", "Party 2 :"))
        self.label_3.setText(_translate("MainWindow", "Party 3 :"))
        self.label_4.setText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "0"))
        self.label_6.setText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "ADD VOTER"))
        self.label_8.setText(_translate("MainWindow", "NAME :"))
        self.label_9.setText(_translate("MainWindow", "Voter ID no. :"))
        self.pushButton.setText(_translate("MainWindow", "Register Voter"))
        self.pushButton.clicked.connect(self.registerVoter)

        self.label_10.setText(_translate("MainWindow", "ADD PARTY"))
        self.label_11.setText(_translate("MainWindow", "PARTY NAME :"))
        self.label_12.setText(_translate("MainWindow", "PARTY HEAD :"))
        self.pushButton_2.setText(_translate("MainWindow", "Register Party"))
        self.pushButton_2.clicked.connect(self.registerParty)

        self.pushButton_3.setText(_translate("MainWindow", "Show Results"))
        self.pushButton_3.clicked.connect(self.showTotalvotes)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
