# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'User.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pymysql


class Ui_MainWindow(object):
    
# database connection
    def dbcon(self):
        con = pymysql.connect(host="localhost", user="root",
                        password="", db="votingdb")
        return con

    def message(self, title, msg):
        window = QtWidgets.QMessageBox()
        window.setWindowTitle(title)
        window.setText(msg)
        window.setStandardButtons(QtWidgets.QMessageBox.Ok)
        window.exec_()

    def submitVote(self):
        con = self.dbcon()
        cursor = con.cursor()
        voterName = self.lineEdit.text()
        voterId = self.lineEdit_2.text()


        checkReg = "select * from voter where voter_card = %s and voter_name = %s"
        cursor.execute(checkReg,(voterId,voterName))
        countReg = cursor.rowcount

        checkVote = "select * from votes where voter_card = %s and voter_name = %s"
        cursor.execute(checkVote,(voterId,voterName))
        countVote = cursor.rowcount

        if countReg!=1:
                self.message("Error","Not Registered Voter")

        elif countVote == 1:
                self.message("Error","Already Voted")

        elif self.radioButton.isChecked():
                vote = "Party1"
                insert = "insert into votes(vote_party,voter_name,voter_card) values(%s,%s,%s)"
                run = cursor.execute(insert,(vote,voterName,voterId))
                if run:
                        self.message("Thank you","Vote Registered")

        elif self.radioButton_2.isChecked():
                vote = "Party2"
                insert = "insert into votes(vote_party,voter_name,voter_card) values(%s,%s,%s)"
                run = cursor.execute(insert,(vote,voterName,voterId))
                if run:
                        self.message("Thank you","Vote Registered")

        elif self.radioButton_3.isChecked():
                vote = "Party3"
                insert = "insert into votes(vote_party,voter_name,voter_card) values(%s,%s,%s)"
                run = cursor.execute(insert,(vote,voterName,voterId))
                if run:
                        self.message("Thank you","Vote Registered")

        con.commit()
        con.close()





    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 432)
        MainWindow.setStyleSheet("background-color: rgb(171, 196, 223);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 30, 211, 41))
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("font-size:20px;\n"
"background-color: rgb(85, 170, 255);\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid white;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 110, 181, 41))
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("color:white;\n"
"font-size:20px;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 170, 181, 41))
        self.label_3.setAutoFillBackground(False)
        self.label_3.setStyleSheet("color:white;\n"
"font-size:20px;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(290, 240, 211, 41))
        self.label_4.setAutoFillBackground(False)
        self.label_4.setStyleSheet("font-size:20px;\n"
"background-color: rgb(0, 85, 127);\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid;\n"
"border-color: rgb(92, 106, 120);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(120, 306, 91, 31))
        self.radioButton.setStyleSheet("font-size:20px;\n"
"background-color: rgb(255, 255, 255);")
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(350, 308, 91, 31))
        self.radioButton_2.setStyleSheet("font-size:20px;\n"
"background-color: rgb(255, 255, 255);")
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_3.setGeometry(QtCore.QRect(580, 310, 91, 31))
        self.radioButton_3.setStyleSheet("font-size:20px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.radioButton_3.setObjectName("radioButton_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(260, 120, 451, 31))
        self.lineEdit.setAutoFillBackground(False)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(260, 180, 451, 31))
        self.lineEdit_2.setAutoFillBackground(False)
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(80, 260, 641, 91))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:2px solid rgb(92, 106, 120);\n"
"border-radius:10px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(330, 379, 131, 31))
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("font-size:20px;\n"
"background-color: rgb(0, 0, 255);\n"
"color: rgb(255, 255, 255);\n"
"border:2px solid white;")
        self.pushButton.setObjectName("pushButton")
        self.frame.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.radioButton.raise_()
        self.radioButton_2.raise_()
        self.radioButton_3.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.pushButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "User Section"))
        self.label.setText(_translate("MainWindow", "Voting Application"))
        self.label_2.setText(_translate("MainWindow", "Name :"))
        self.label_3.setText(_translate("MainWindow", "Voter ID card no. :"))
        self.label_4.setText(_translate("MainWindow", "SELECT VOTE"))
        self.radioButton.setText(_translate("MainWindow", "Party 1"))
        self.radioButton_2.setText(_translate("MainWindow", "Party 2"))
        self.radioButton_3.setText(_translate("MainWindow", "Party 3"))
        self.pushButton.setText(_translate("MainWindow", "Submit Vote"))
        self.pushButton.clicked.connect(self.submitVote)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
